### PR TITLE
Update 0.15.0

### PR DESCRIPTION
**Pull request by Arishamays1**
# ❄️☆Streanlit-folium 0.15.0 Update ☆❄️
[Jira Ticket](https://anaconda.atlassian.net/browse/PKG-3086)
[Upstream](https://github.com/randyzwitch/streamlit-folium)
[Dependencies ](https://github.com/randyzwitch/streamlit-folium/blob/master/setup.py)
# Changes
- Updated version number and `sha256`
- Updated pinnings on dependencies
- Skip for `s390x`

### CODE REVIEW

**Comment by lorepirri** [comment]
@Arishamays1 on `s390x` the build fails because the dependency `streamlit` is not found ([because it was not built](https://github.com/AnacondaRecipes/streamlit-feedstock/blob/6ab5633c2db58e75d6912677949b0dc707d7a1ec/recipe/meta.yaml#L17) for `s390x`): you can skip it.

```
                   INFO     File "/opt/conda/lib/python3.9/site-packages/conda/resolve.py", line 286, in verify_specs                                                                                             
                   INFO       raise ResolvePackageNotFound(bad_deps)                                                                                                                                              
                   INFO   conda.exceptions.ResolvePackageNotFound:                                                                                                                                                
                   INFO     - streamlit[version='>=1.13']                                                                                                                                                         
                   INFO                                                                                                                                                                                           
                   INFO   During handling of the above exception, another exception occurred:                                                                                                                     
                   INFO                                 
```

**Comment by Arishamays1** [comment]
> @Arishamays1 on `s390x` the build fails because the dependency `streamlit` is not found ([because it was not built](https://github.com/AnacondaRecipes/streamlit-feedstock/blob/6ab5633c2db58e75d6912677949b0dc707d7a1ec/recipe/meta.yaml#L17) for `s390x`): you can skip it.
> 
> ```
>                    INFO     File "/opt/conda/lib/python3.9/site-packages/conda/resolve.py", line 286, in verify_specs                                                                                             
>                    INFO       raise ResolvePackageNotFound(bad_deps)                                                                                                                                              
>                    INFO   conda.exceptions.ResolvePackageNotFound:                                                                                                                                                
>                    INFO     - streamlit[version='>=1.13']                                                                                                                                                         
>                    INFO                                                                                                                                                                                           
>                    INFO   During handling of the above exception, another exception occurred:                                                                                                                     
>                    INFO                                 
> ```

Got it! Made some changes

**Review by lorepirri — APPROVED** [review]
LGTM!

**Review by lorepirri — APPROVED** [review]
ah the `abs.yaml` for SF

**Comment by Arishamays1** [comment]
> ah the `abs.yaml` for SF

According to the ticket it was supposed to go to defaults! Can we reconfirm this?

**Review by ViridianMelody — APPROVED** [review]

**Pull request merged**
